name: Deploy Node.js app to VPS

on:
  push:
    branches:
      - master  # or main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no root@31.97.61.58 '
            cd digitalmarkBE &&
            git pull &&
            npm install &&
            pm2 restart server
          '
