name: Deploy Node.js app to VPS

on:
  push:
    branches:
      - master  # or main

  workflow_dispatch:
    inputs:
      deploy_branch:
        description: 'Branch to deploy'
        required: true
        default: 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no root@31.97.61.58 '
            cd digitalmarkBE &&
            git fetch origin &&
            git checkout ${{ github.event.inputs.deploy_branch || 'master' }} &&
            git pull origin ${{ github.event.inputs.deploy_branch || 'master' }} &&
            npm install &&
            pm2 restart server
          '
